on:
  push:
    branches: [master]

jobs:

  Publish:
    name: Publish NuGet package to GitHub
    runs-on: windows-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Pack
        run: msbuild /t:pack .\CADCodeProxy\CADCodeProxy.csproj
        shell: pwsh

      - name: Publish
        run: dotnet nuget push ".\CADCodeProxy\CADCodeProxy\bin\Release\CADCodeProxy.1.0.0.nupkg" --source "github"