on:
  release:
    types: [published]

jobs:

  Publish:
    name: Publish NuGet package to GitHub
    runs-on: windows-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pack
        run: dotnet pack --configuration Release
        shell: pwsh

      - name: Publish
        run: dotnet nuget push "bin/Release/CADCodeProxy.1.0.0.nupkg" --source "github"